### ISSUE TITLE
Dear Auther, how do you solve the s/cpp/ws-psnr in some projection

### ISSUE THREAD

**Issue by cjhkeep** [Archer-Tatsu/VQA-ODV#1]
It is  brilliant work in vqa dataset, and I read your work in 2017 & 2018.
When I turn to the implement of s/cpp/ws-psnr, It seems it only availabe in ERP projection
and TSP/RCMP is missed by 360tools or oricode by auther.
Do you implement the TSP/RCMP in  s/cpp/ws-psnr, Is there achievable source for those projection?
looking for your reply.

**Comment by Archer-Tatsu** [comment]
Please see https://github.com/Samsung/360tools

**Comment by cjhkeep** [comment]
老哥，我想说中文呀~
我也喜欢FSN，哈哈，FGO氪不动了
我能用邮箱向你提问吗  fz.junhao.chen@gmail.com

**Comment by Archer-Tatsu** [comment]
没问题，我的邮箱是jnlichen123@buaa.edu.cn
（不PY一波FGO吗2333虽然我是国服安卓）

**Comment by cjhkeep** [comment]
老铁，11号FSN有剧场版了~
